name: Pre-Commit

on:
  pull_request:
    branches:
      - main

permissions: write-all

env:
  TERRAFORM_DOCS_VERSION: v0.16.0

jobs:
  collectInputs:
    name: Collect workflow inputs
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get root directories
        id: dirs
        uses: clowdhaus/terraform-composite-actions/directories@b3bb2f7aa1dfca7ffa6373380a7c1b55580b7c7e # v1.8.3

  preCommitMinVersions:
    name: Min TF pre-commit
    needs: collectInputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.collectInputs.outputs.directories) }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@4a93c5af0208f3c76a5d88fa71a065c0852cf304 # v1.2.7
        with:
          directory: ${{ matrix.directory }}

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory !=  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@b3bb2f7aa1dfca7ffa6373380a7c1b55580b7c7e # v1.8.3
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          args: "terraform_validate --color=always --show-diff-on-failure --files ${{ matrix.directory }}/*"

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory ==  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@b3bb2f7aa1dfca7ffa6373380a7c1b55580b7c7e # v1.8.3
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          args: "terraform_validate --color=always --show-diff-on-failure --files $(ls *.tf)"

  preCommitMaxVersion:
    name: Max TF pre-commit
    runs-on: ubuntu-latest
    needs: collectInputs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@4a93c5af0208f3c76a5d88fa71a065c0852cf304 # v1.2.7

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@b3bb2f7aa1dfca7ffa6373380a7c1b55580b7c7e # v1.8.3
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}
          install-hcledit: true
          hcledit-version: 0.2.6
